{% set name = "mbedtls" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ARMmbed/mbedtls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b02df6f68dd1537e115a8497d5c173dc71edc55ad084756e57a30f951b725acd

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - cmake
    - make
    - python  # [osx and build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [osx and build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python  # [osx and build_platform != target_platform]
  run:
    - python  # [osx and build_platform != target_platform]
test:
  commands:
    - mbedtls_hello

about:
  home: https://tls.mbed.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library

extra:
  recipe-maintainers:
    - izahn
